name: MDP.WebApp Deploy to Azure
branding:
  icon: truck
  color: red
author: Clark159
description: GitHub Action for Deploying MDP.WebApp to Azure

inputs:
  azureCredentials:
    description: Azure Credentials
    required: true
    
  resourceGroupName:
    description: Resource Group Name
    required: true
    
  registryServerName:
    description: Registry Server Name
    required: true

  dockerFilePath:
    description: Docker File Path
    required: true

  containerAppName:
    description: Container App Name
    required: true

  containerLogName:
    description: container Log Name
    required: true

  containerEnvName:
    description: Container Environment Name
    required: true
    
runs:
  using: composite
  steps:
  
  - name: Login Azure CLI
    uses: azure/login@v1
    with:
      creds: ${{ inputs.azureCredentials }}

  - name: Azure Container Registry Build by MDP             
    uses: MDPOps/azure-container-registry-build@v1
    with:
      resourceGroupName: ${{ inputs.resourceGroupName }}
      registryServerName: ${{ inputs.registryServerName }}
      dockerImageName: ${{ inputs.containerAppName }}
      dockerFilePath: ${{ inputs.dockerFilePath }}

  - name: Azure Container Apps Deploy by MDP
    uses: MDPOps/azure-container-apps-deploy@v1
    with:
      resourceGroupName: ${{ inputs.resourceGroupName }}
      registryServerName: ${{ inputs.registryServerName }}
      dockerImageName: ${{ inputs.containerAppName }}
      containerAppName: ${{ inputs.containerAppName }}
      containerLogName: ${{ inputs.containerLogName }}
      containerEnvName: ${{ inputs.containerEnvName }}